version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: [ "sh", "-c", "chmod +x ./run.sh && ./run.sh" ]
    environment:
      - ENV=dev
    networks:
      - app-net

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python -m src.worker
    volumes:
      - ./server:/app
    environment:
      - ENV=dev
    networks:
      - app-net
    depends_on:
      - server

networks:
  app-net:
    driver: bridge
